// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYCd2GeGleF1sFSZ0or6MpvZd-0Ol9p5A',
    appId: '1:761608570710:web:3d8e9995e26e2186dab8f7',
    messagingSenderId: '761608570710',
    projectId: 'nyobak-bec2b',
    authDomain: 'nyobak-bec2b.firebaseapp.com',
    storageBucket: 'nyobak-bec2b.appspot.com',
    measurementId: 'G-CBVD9Q3HVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9OAr3LhvTEhFZYUllJ2lMdWDdWuhyEC4',
    appId: '1:761608570710:android:15a14c3aacfc433cdab8f7',
    messagingSenderId: '761608570710',
    projectId: 'nyobak-bec2b',
    storageBucket: 'nyobak-bec2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoTeydHxl9ngNp8BA4z9VEVznVlQtyurg',
    appId: '1:761608570710:ios:db5bc130c2bf06b3dab8f7',
    messagingSenderId: '761608570710',
    projectId: 'nyobak-bec2b',
    storageBucket: 'nyobak-bec2b.appspot.com',
    iosBundleId: 'com.example.flutterApplication4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoTeydHxl9ngNp8BA4z9VEVznVlQtyurg',
    appId: '1:761608570710:ios:ce936693dbd18592dab8f7',
    messagingSenderId: '761608570710',
    projectId: 'nyobak-bec2b',
    storageBucket: 'nyobak-bec2b.appspot.com',
    iosBundleId: 'com.example.flutterApplication4.RunnerTests',
  );
}
