// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLICS9LkVuKdZlDs15WVQKSPlfwBoj0GI',
    appId: '1:408942475699:web:8417ac5a774a2277df73c6',
    messagingSenderId: '408942475699',
    projectId: 'belajar-crud-2a526',
    authDomain: 'belajar-crud-2a526.firebaseapp.com',
    storageBucket: 'belajar-crud-2a526.appspot.com',
    measurementId: 'G-SN7CZM1FLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeFKcVOz1Y1TJ-jRSZjGXGhXVlrO0D4Is',
    appId: '1:408942475699:android:c7151aad7035e429df73c6',
    messagingSenderId: '408942475699',
    projectId: 'belajar-crud-2a526',
    storageBucket: 'belajar-crud-2a526.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAw_5OYbPz87YVNSeWUCvy7fDX6oZMoUg',
    appId: '1:408942475699:ios:cd455c8e2caf27ccdf73c6',
    messagingSenderId: '408942475699',
    projectId: 'belajar-crud-2a526',
    storageBucket: 'belajar-crud-2a526.appspot.com',
    iosBundleId: 'com.example.belajarCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAw_5OYbPz87YVNSeWUCvy7fDX6oZMoUg',
    appId: '1:408942475699:ios:faa1b2dd2829f22adf73c6',
    messagingSenderId: '408942475699',
    projectId: 'belajar-crud-2a526',
    storageBucket: 'belajar-crud-2a526.appspot.com',
    iosBundleId: 'com.example.belajarCrud.RunnerTests',
  );
}
